### ISSUE TITLE
Error in data processing step

### ISSUE THREAD

**Issue by ghost** [henryxrl/Listening-to-Sound-of-Silence-for-Speech-Denoising#1]
I am trying to run your code. I installed all of the requirements, and then in the phase of data processing, I defined the directories in preprocessor_audioonly.py file as (I edited only this part below)
```
SNR = [-10, -7, -3, 0, 3, 7, 10]
for snr in tqdm(SNR):
    #DIR = '/proj/vondrick/rx2132/test_noise_robust_embedding/data/TIMIT/TEST_noisy_snr' + str(int(snr))
    DIR = '/home/mehri/data/PycharmProjects/denoise/data/sounds_of_silence_audioonly' + str(int(snr))
    CSV = '/home/mehri/data/PycharmProjects/denoise/data/sounds_of_silence_audioonly' + str(int(snr)) + '/sounds_of_silence' + str(int(snr)) + '.csv'
    build_csv(DIR, CSV, ext='.WAV')
    JSON = '/home/mehri/data/PycharmProjects/denoise/data/sounds_of_silence_audioonly' + str(int(snr)) + '.json'
    build_json_better(DIR, CSV, JSON, ext='.WAV')
```

But I get the error 
```
Traceback (most recent call last):
  File "<input>", line 2, in <module>
NameError: name 'tqdm' is not defined

```

**Comment by henryxrl** [comment]
Have you installed tqdm package?
`pip install tqdm`

**Comment by ghost** [comment]
Thanks for your response. Yes I have installed tqdm and now I am getting the error :

```
Traceback (most recent call last):
  File "<input>", line 14, in <module>
NameError: name 'AUDIO_EXT' is not defined
```

**Comment by henryxrl** [comment]
AUDIO_EXT is a variable that defines the extension of audio files. In this case it's '.wav'. You can search for it and define your own according to your needs.

**Comment by mehrisajjadian** [comment]
I change
```
def process_audio(csv_path, output_dir, audio_id, output_json, ext=AUDIO_EXT, print_progress=True):
```
to 
```
def process_audio(csv_path, output_dir, audio_id, output_json, ext=WAV, print_progress=True):
but I get the error;
```
Traceback (most recent call last):
  File "<input>", line 2, in <module>
NameError: name 'WAV' is not defined
```

**Comment by ghost** [comment]
I changed all of the AUDIO_EXT to .wav such as
```
def process_audio(csv_path, output_dir, audio_id, output_json, ext=.wav, print_progress=True):
```
I get the error :
  File "<input>", line 14
    def process_audio(csv_path, output_dir, audio_id, output_json, ext=.wav, print_progress=True):
                                                                       ^
SyntaxError: invalid syntax
```

**Comment by henryxrl** [comment]
'.wav' is a string.

**Comment by mehrisajjadian** [comment]
My mistake. Corrected. Error in :
```
    SNR = [-10, -7, -3, 0, 3, 7, 10]
    for snr in tqdm(SNR):
        # DIR = '/proj/vondrick/rx2132/test_noise_robust_embedding/data/TIMIT/TEST_noisy_snr' + str(int(snr))
        DIR = '/home/mehri/data/PycharmProjects/denoise/data/sounds_of_silence_audioonly' + str(int(snr))
        CSV = '/home/mehri/data/PycharmProjects/denoise/data/sounds_of_silence_audioonly' + str(
            int(snr)) + '/sounds_of_silence' + str(int(snr)) + '.csv'
        build_csv(DIR, CSV, ext='.WAV')
        JSON = '/home/mehri/data/PycharmProjects/denoise/data/sounds_of_silence_audioonly' + str(int(snr)) + '.json'
        build_json_better(DIR, CSV, JSON, ext='.WAV')
```
Error:
```
0%|          | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<input>", line 7, in <module>
  File "<input>", line 164, in build_csv
FileNotFoundError: [Errno 2] No such file or directory: '/home/mehri/data/PycharmProjects/denoise/data/sounds_of_silence_audioonly-10/sounds_of_silence-10.csv'
```

**Comment by henryxrl** [comment]
As the error indicates, there's no such file at your provided location. These all look like errors that are unrelated to the code itself. I'm sure you can figure these out by yourself. Good luck! :-)

**Comment by ghost** [comment]
But I am trying to run the code with the example data and explanation you provided. Only one csv is provided and it is sounds_of_silence.csv. I have to give up at this stage. But I will wait to see if anyone can run this code. 
Error:
  0%|          | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<input>", line 188, in <module>
  File "<input>", line 164, in build_csv
FileNotFoundError: [Errno 2] No such file or directory: '/home/mehri/data/PycharmProjects/denoise/data/sounds_of_silence_audioonly-10/sounds_of_silence-10.csv'

Note that there is discrepancy in the code and provided example data that leads to many errors.

**Comment by henryxrl** [comment]
If you use the provided data sample, then you don't need to run the data preprocessing step. All you need to do is to change the file locations inside the csv to point to the correct location where you save all the wav files.
