### ISSUE TITLE
pretrain model

### ISSUE THREAD

**Issue by trinhdnk95** [henryxrl/Listening-to-Sound-of-Silence-for-Speech-Denoising#10]
I'm trying to find the pretrained weights in the Sourcecode.

However, the link to the Pretrained weights didn't work.

So where can I find it?

**Comment by anitaweng** [comment]
Maybe you can try to copy the URL from the link and paste it to your search engine.
I tried this method, and it worked.

**Comment by henryxrl** [comment]
It does work for me. Maybe try what @anitaweng suggested. Closing now.
