### ISSUE TITLE
What to do about pre-trained models and the ckpt argument?

### ISSUE THREAD

**Issue by andreev-io** [henryxrl/Listening-to-Sound-of-Silence-for-Speech-Denoising#3]
I carefully read the paper and loved it. I got most of the way through to make the code work for my use case, but I can't figure out what the purpose of the `ckpt` parameter is.

Following the steps and fixing things along the way, I inevitably get to 
`FileNotFoundError: [Errno 2] No such file or directory: '../model_output/audioonly_model/model/ckpt_epoch87.pth'`, which should be of no surprise, but I'm clueless as to what the workaround should be.

Any guidance here please?

**Comment by andreev-io** [comment]
Never mind, I simply commented out the code that loads check points. Will report here once I get the models to run.

**Comment by antonelse** [comment]
Hi, did you get the checkpoints at the end? I couldn’t find anything on the web.

Thanks !!

**Comment by antonelse** [comment]
> Never mind, I simply commented out the code that loads check points. Will report here once I get the models to run.

Hi, did you get the checkpoints at the end? I couldn’t find anything on the web.
I’m having a hard time fixing the errors.
Do you have any suggestions for training the model?

Thanks in advance !!
