### ISSUE TITLE
Pretrained checkpoints availability

### ISSUE THREAD

**Issue by yossing-audatic** [henryxrl/Listening-to-Sound-of-Silence-for-Speech-Denoising#4]
Hi, are the pretrained model checkpoints you used to produce the results in the paper available for download? Running the code snippets you provided in the inference section fail because ckpt 87 and ckpt 24 are not in the model_output directories. Thanks!

**Comment by antonelse** [comment]
Same request here ! 
Thanks !

**Comment by henryxrl** [comment]
It's now available [here](http://www.cs.columbia.edu/cg/listen_to_the_silence/pretrained/pretrained.zip).
