### ISSUE TITLE
metrics

### ISSUE THREAD

**Issue by yunzqq** [henryxrl/Listening-to-Sound-of-Silence-for-Speech-Denoising#9]
I have a issue about the pesq metrics. I see that you use the pypesq package to compute the pesq. But this package just can compute narrow band pesq version. The demand dataset is 16k sampling rate and the baseline model also provide the wide band pesq version. The two values will be different. And also the other three metrics related to pesq will be different. Does author note sunch things?

**Comment by aloha0920** [comment]
same issue here

**Comment by henryxrl** [comment]
Yes. The metric provided is narrow-band only.
